repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.6
  - repo: git://github.com/doublify/pre-commit-isort
    rev: master
    hooks:
    -   id: isort
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: check-merge-conflict