# Config file for automatic testing at travis-ci.org

sudo: true

dist: trusty

services:
  - docker
  - postgresql

env:
  global:
    - DOCKER_REPO_URL=quay.io
    - DOCKER_REPO_OWNER=lookit
    - DOCKER_REPO_NAME=lookit-api
    - DOCKER_BRANCH=${TRAVIS_BRANCH/\//-}
    - DOCKER_IMAGE_URL=$DOCKER_REPO_URL/$DOCKER_REPO_OWNER/$DOCKER_REPO_NAME

cache:
  directories:
    - $HOME/docker

notifications:
  slack: lookit-mit:Sc6ZVxrtb0vIiXtft93BtXNI

addons:
  postgresql: "9.6.16"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

jobs:
  include:
    - stage: Build & Test
      script:
        - docker pull $DOCKER_IMAGE_URL:$TRAVIS_COMMIT || docker pull $DOCKER_IMAGE_URL:$DOCKER_BRANCH || true
        - docker build
            --cache-from $DOCKER_IMAGE_URL:$TRAVIS_COMMIT --cache-from $DOCKER_IMAGE_URL:$DOCKER_BRANCH
            --build-arg GIT_COMMIT=$TRAVIS_COMMIT --build-arg GIT_TAG=$TRAVIS_TAG
            --pull -t $DOCKER_IMAGE_URL:$TRAVIS_COMMIT .
        - docker run --rm -it -p 5432:5432 $DOCKER_IMAGE_URL:$TRAVIS_COMMIT python manage.py test
