steps:
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - -t
  - gcr.io/$PROJECT_ID/lookit-api:${TAG_NAME}${BRANCH_NAME}
  - '.'

images:
- gcr.io/$PROJECT_ID/lookit-api:${TAG_NAME}${BRANCH_NAME}